### ISSUE TITLE
Message Details tab cannot display IPv6 addresses

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-view#14]
... in three displayed fields taken from within a SIP packet.

e.g. for an `OPTIONS` packet which displays as follows:

from_domain | [2001
-- | --

ruri_domain | [2001
-- | --

to_domain | [2001
-- | --

These fields display correctly, they are derived from the HEP packet (I think):

dstIp | ...
-- | --

srcIp | ...
-- | --

**Comment by mikegoodstadt** [comment]
Hi - can you confirm that this is the issue fixed in #19 ? Thanks

**Comment by systemcrash** [comment]
Problem remains. A problem packet where this manifests looks like:

```
REGISTER sip:[fda3:c19:eb4f:bf19::1] SIP/2.0
Via: SIP/2.0/UDP [fd75:f48b:d3e6:37fb:3c9e:c34:b0a1:44de]:63063;branch=z9hG4bK-524287-1---b281411bb3c4dc41;received=fda3:c19:eb4f:bf19::8:101;rport=63063
Max-Forwards: 70
Contact: <sip:user@[fd75:f48b:d3e6:37fb:3c9e:c34:b0a1:44de]:63063;rinstance=5083dd822e007f97>
To: <sip:user@[fda3:c19:eb4f:bf19::1]>
From: <sip:user@[fda3:c19:eb4f:bf19::1]>;tag=e8228156
Call-ID: 102649NWJkY2FhMTY2ZmFlYjBkMjRhMTExMmZjM2QxY2Y0YjU
CSeq: 1 REGISTER
Expires: 3600
Allow: OPTIONS, SUBSCRIBE, NOTIFY, INVITE, ACK, CANCEL, BYE, REFER, INFO, MESSAGE
User-Agent: Some UA
Content-Length: 0
```

Display code for those 'message detail' fields is different (I think) from my fix in #19

**Comment by systemcrash** [comment]
#19 did fix the problem for IPv6 addresses displayed at the top of the call graph. So code there may be of some help to you.

**Comment by mikegoodstadt** [comment]
Ok - will look into it. Thanks!

**Comment by jacovinus** [comment]
Closing. Fixed with : https://github.com/sipcapture/homer-view/commit/9c8d82e2ee8206325922d082eddc5378fa495a3f
